import Foundation

/// What clipboard history must never keep. Three layers: the pasteboard's own
/// markers (password managers flag what they copy, per nspasteboard.org), the
/// app it came from, and the text itself (cards, keys, tokens, one-time codes).
public enum ClipboardPrivacy {
  /// Types an app adds to say "don't remember this".
  public static let markerTypes: Set<String> = [
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
    "de.petermaurer.TransientPasteboardType",
    "com.typeit4me.clipping",
    "Pasteboard generator type",
    "net.antelle.keeweb",
  ]

  /// Password managers and the like: anything copied while they're in front is skipped.
  public static let privateApps: Set<String> = [
    "com.apple.keychainaccess",
    "com.apple.Passwords",
    "com.1password.1password",
    "com.agilebits.onepassword7",
    "com.agilebits.onepassword-osx",
    "com.bitwarden.desktop",
    "com.lastpass.LastPass",
    "com.dashlane.dashlanephonefinal",
    "com.dashlane.Dashlane",
    "org.keepassxc.keepassxc",
    "com.enpass.Enpass-Desktop",
    "com.nordpass.macos.NordPass",
    "me.proton.pass.electron",
    "in.sinew.Enpass-Desktop",
  ]

  /// Whether an item should be skipped before even reading it.
  public static func skips(types: [String], sourceBundle: String?) -> Bool {
    if types.contains(where: markerTypes.contains) { return true }
    if let sourceBundle, privateApps.contains(sourceBundle) { return true }
    return false
  }

  /// The text looks like a secret. Deliberately conservative about prose and
  /// code: only whole-clipboard tokens trip it, never a sentence that happens
  /// to contain a number.
  public static func looksSensitive(_ raw: String) -> Bool {
    let text = raw.trimmingCharacters(in: .whitespacesAndNewlines)
    guard !text.isEmpty else { return false }
    if text.contains("-----BEGIN") && text.contains("PRIVATE KEY") { return true }
    if text.count > 4000 { return false }
    // A card number: 13–19 digits, maybe spaced or dashed, passing Luhn.
    let digits = text.filter(\.isNumber)
    let cardShaped = text.allSatisfy { $0.isNumber || $0 == " " || $0 == "-" }
    if cardShaped, (13...19).contains(digits.count), luhn(digits) { return true }
    // A one-time code: a lone 6–8 digit number.
    if text.allSatisfy(\.isNumber), (6...8).contains(text.count) { return true }
    guard !text.contains(where: \.isWhitespace) else { return false }
    for pattern in tokenPatterns where text.range(of: pattern, options: .regularExpression) != nil { return true }
    return looksLikePassword(text)
  }

  /// Well-known credential shapes, anchored to the whole clipboard.
  static let tokenPatterns: [String] = [
    #"^sk-[A-Za-z0-9_\-]{20,}$"#,  // OpenAI / Anthropic style
    #"^sk-ant-[A-Za-z0-9_\-]{20,}$"#,
    #"^gh[pousr]_[A-Za-z0-9]{30,}$"#,  // GitHub
    #"^github_pat_[A-Za-z0-9_]{30,}$"#,
    #"^xox[abprs]-[A-Za-z0-9-]{10,}$"#,  // Slack
    #"^AKIA[0-9A-Z]{16}$"#,  // AWS access key
    #"^AIza[0-9A-Za-z_\-]{35}$"#,  // Google API key
    #"^glpat-[A-Za-z0-9_\-]{20,}$"#,  // GitLab
    #"^eyJ[A-Za-z0-9_\-]+\.eyJ[A-Za-z0-9_\-]+\.[A-Za-z0-9_\-]+$"#,  // JWT
    #"^(sk|rk|pk)_(live|test)_[A-Za-z0-9]{16,}$"#,  // Stripe
  ]

  /// One short token mixing all four character classes, that isn't a URL,
  /// path, email or identifier-like word: probably a generated password.
  static func looksLikePassword(_ text: String) -> Bool {
    guard (10...64).contains(text.count) else { return false }
    if text.contains("://") || text.contains("/") || text.contains("@") || text.hasPrefix(".") { return false }
    let upper = text.contains(where: \.isUppercase)
    let lower = text.contains(where: \.isLowercase)
    let digit = text.contains(where: \.isNumber)
    let symbol = text.contains { !$0.isLetter && !$0.isNumber }
    guard upper && lower && digit && symbol else { return false }
    // Code like `fooBar1(x)` or `a.b_c2` isn't a password: symbols there are punctuation.
    let codeish = text.contains("(") || text.contains(")") || text.contains(";") || text.contains("=")
    return !codeish
  }

  public static func luhn(_ digits: String) -> Bool {
    var sum = 0
    for (index, character) in digits.reversed().enumerated() {
      guard var d = character.wholeNumberValue else { return false }
      if index % 2 == 1 {
        d *= 2
        if d > 9 { d -= 9 }
      }
      sum += d
    }
    return sum % 10 == 0
  }
}

/// The history itself: newest first, no duplicates, capped.
public struct ClipboardLog<Item: Equatable & Sendable>: Sendable {
  public private(set) var items: [Item] = []
  public var limit: Int

  public init(limit: Int = 30) {
    self.limit = limit
  }

  /// Puts `item` at the top; an equal older copy moves up instead of repeating.
  public mutating func add(_ item: Item) {
    items.removeAll { $0 == item }
    items.insert(item, at: 0)
    if items.count > limit { items.removeLast(items.count - limit) }
  }

  public mutating func remove(where match: (Item) -> Bool) {
    items.removeAll(where: match)
  }

  public mutating func clear() {
    items.removeAll()
  }
}
